/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/Aside/aside.vue')['default']
    Dialog: typeof import('./src/components/Dialog/dialog.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElWatermark: typeof import('element-plus/es')['ElWatermark']
    Link: typeof import('./src/components/Else/link.vue')['default']
    Middle: typeof import('./src/components/Music/Middle.vue')['default']
    MusicList: typeof import('./src/components/MusicForGet/MusicList.vue')['default']
    Play: typeof import('./src/components/Music/Play.vue')['default']
    PlayMusic: typeof import('./src/components/MusicForGet/PlayMusic.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongDetail: typeof import('./src/components/MusicForGet/SongDetail.vue')['default']
    Test: typeof import('./src/components/Else/Test.vue')['default']
  }
}
